// Code generated by MockGen. DO NOT EDIT.
// Source: file.go

// Package file is a generated GoMock package.
package file

import (
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	file "github.com/hildam/AI-Cloud-Drive/dao/file"
)

// MockLogic is a mock of Logic interface.
type MockLogic struct {
	ctrl     *gomock.Controller
	recorder *MockLogicMockRecorder
}

// MockLogicMockRecorder is the mock recorder for MockLogic.
type MockLogicMockRecorder struct {
	mock *MockLogic
}

// NewMockLogic creates a new mock instance.
func NewMockLogic(ctrl *gomock.Controller) *MockLogic {
	mock := &MockLogic{ctrl: ctrl}
	mock.recorder = &MockLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogic) EXPECT() *MockLogicMockRecorder {
	return m.recorder
}

// BatchMoveFiles mocks base method.
func (m *MockLogic) BatchMoveFiles(userID uint, fileIDs []string, targetParentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchMoveFiles", userID, fileIDs, targetParentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchMoveFiles indicates an expected call of BatchMoveFiles.
func (mr *MockLogicMockRecorder) BatchMoveFiles(userID, fileIDs, targetParentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchMoveFiles", reflect.TypeOf((*MockLogic)(nil).BatchMoveFiles), userID, fileIDs, targetParentID)
}

// CreateFolder mocks base method.
func (m *MockLogic) CreateFolder(userID uint, name string, parentID *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFolder", userID, name, parentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFolder indicates an expected call of CreateFolder.
func (mr *MockLogicMockRecorder) CreateFolder(userID, name, parentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFolder", reflect.TypeOf((*MockLogic)(nil).CreateFolder), userID, name, parentID)
}

// DeleteFileOrFolder mocks base method.
func (m *MockLogic) DeleteFileOrFolder(userID uint, fileID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFileOrFolder", userID, fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFileOrFolder indicates an expected call of DeleteFileOrFolder.
func (mr *MockLogicMockRecorder) DeleteFileOrFolder(userID, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileOrFolder", reflect.TypeOf((*MockLogic)(nil).DeleteFileOrFolder), userID, fileID)
}

// DownloadFile mocks base method.
func (m *MockLogic) DownloadFile(fileID string) (*file.File, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", fileID)
	ret0, _ := ret[0].(*file.File)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockLogicMockRecorder) DownloadFile(fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockLogic)(nil).DownloadFile), fileID)
}

// GetFileByID mocks base method.
func (m *MockLogic) GetFileByID(fileID string) (*file.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByID", fileID)
	ret0, _ := ret[0].(*file.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByID indicates an expected call of GetFileByID.
func (mr *MockLogicMockRecorder) GetFileByID(fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByID", reflect.TypeOf((*MockLogic)(nil).GetFileByID), fileID)
}

// GetFileIDPath mocks base method.
func (m *MockLogic) GetFileIDPath(fileID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileIDPath", fileID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileIDPath indicates an expected call of GetFileIDPath.
func (mr *MockLogicMockRecorder) GetFileIDPath(fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileIDPath", reflect.TypeOf((*MockLogic)(nil).GetFileIDPath), fileID)
}

// GetFilePath mocks base method.
func (m *MockLogic) GetFilePath(fileID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilePath", fileID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilePath indicates an expected call of GetFilePath.
func (mr *MockLogicMockRecorder) GetFilePath(fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilePath", reflect.TypeOf((*MockLogic)(nil).GetFilePath), fileID)
}

// GetFileURL mocks base method.
func (m *MockLogic) GetFileURL(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileURL", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileURL indicates an expected call of GetFileURL.
func (mr *MockLogicMockRecorder) GetFileURL(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileURL", reflect.TypeOf((*MockLogic)(nil).GetFileURL), key)
}

// InitKnowledgeDir mocks base method.
func (m *MockLogic) InitKnowledgeDir(userID uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitKnowledgeDir", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitKnowledgeDir indicates an expected call of InitKnowledgeDir.
func (mr *MockLogicMockRecorder) InitKnowledgeDir(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitKnowledgeDir", reflect.TypeOf((*MockLogic)(nil).InitKnowledgeDir), userID)
}

// PageList mocks base method.
func (m *MockLogic) PageList(userID uint, parentID *string, page, pageSize int, sort string) (int64, []file.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PageList", userID, parentID, page, pageSize, sort)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]file.File)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PageList indicates an expected call of PageList.
func (mr *MockLogicMockRecorder) PageList(userID, parentID, page, pageSize, sort interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PageList", reflect.TypeOf((*MockLogic)(nil).PageList), userID, parentID, page, pageSize, sort)
}

// Rename mocks base method.
func (m *MockLogic) Rename(userID uint, fileID, newName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", userID, fileID, newName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockLogicMockRecorder) Rename(userID, fileID, newName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockLogic)(nil).Rename), userID, fileID, newName)
}

// SearchList mocks base method.
func (m *MockLogic) SearchList(userID uint, key string, page, size int, sort string) (int64, []file.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchList", userID, key, page, size, sort)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]file.File)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchList indicates an expected call of SearchList.
func (mr *MockLogicMockRecorder) SearchList(userID, key, page, size, sort interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchList", reflect.TypeOf((*MockLogic)(nil).SearchList), userID, key, page, size, sort)
}

// UploadFile mocks base method.
func (m *MockLogic) UploadFile(userID uint, fileHeader *multipart.FileHeader, file multipart.File, parentID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", userID, fileHeader, file, parentID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockLogicMockRecorder) UploadFile(userID, fileHeader, file, parentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockLogic)(nil).UploadFile), userID, fileHeader, file, parentID)
}
